### ISSUE TITLE
CURL_AUTH error

### ISSUE THREAD

**Issue by andrewwang79** [ryandaniels/docker-script-find-latest-image-tag#1]
I got the error when execute this command. thanks!

# sh docker_image_find_tag.sh -n mongo -i 87f1a6e84e00
docker_image_find_tag.sh: line 175: CURL_AUTH[@]: unbound variable

**Comment by duanqn** [comment]
I think it's because `sh` doesn't support arrays. Can you try running it with `bash`? The first line of the script clearly shows it should be executed in `bash`.

**Comment by saitharunkumar10** [comment]
> I got the error when execute this command. thanks!
> 
> # sh docker_image_find_tag.sh -n mongo -i 87f1a6e84e00
> docker_image_find_tag.sh: line 175: CURL_AUTH[@]: unbound variable

did you resolve this issue?

**Comment by skyhos** [comment]
Same issue on centos7, bash.
I've tried to execute the script after I logged in manually.
```
$ ./docker_tag_finder.sh -n haproxy -i ecf07e33b5c4 -f 2. -l 10 -v
Using IMAGE_NAME: haproxy
Using REGISTRY: https://index.docker.io/v2
Found Image ID Source: sha256:ecf07e33b5c4bbb59188bf77781c047d9ff8accdf21b1902212b4c04864982a8
./docker_tag_finder.sh: line 172: CURL_AUTH[@]: unbound variable
```

**Comment by ryandaniels** [comment]
Should be fixed now. Something weird going on with older versions of Bash.
